/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatePresence: typeof import('motion-v')['AnimatePresence']
    NButton: typeof import('naive-ui')['NButton']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NResult: typeof import('naive-ui')['NResult']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AnimatePresence: typeof import('motion-v')['AnimatePresence']
  const NButton: typeof import('naive-ui')['NButton']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NResult: typeof import('naive-ui')['NResult']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}