name: Lint

on:
  push:
    paths:
      - packages

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true

      - name: Install dependencies
        run: vp install

      - name: Lint
        run: |
          vp run npm-build
          vp check