name: 单元测试

on:
  push:
    paths:
      - 'packages/**'
      - 'script/**'
      - '.github/workflows/test.yaml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '*.config.ts'
      - 'tsconfig*.json'
  pull_request:
    paths:
      - 'packages/**'
      - 'script/**'
      - '.github/workflows/test.yaml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '*.config.ts'
      - 'tsconfig*.json'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          cache: true

      - name: Install dependencies
        run: vp install

      - name: Test
        run: |
          vp run lib-build
          vp test run